### ISSUE TITLE
Argument passthrough

### ISSUE THREAD

**Issue by KaranveerB** [KaranveerB/srun#6]
Would be nice to passthrough arguments to either be parsed by a called program/script, or allow it to be directly inserted into the command. E.g.,

```toml
# idea 1
regular = { command = "echo", args = "*" }
# idea 2
insert = { command = "echo $1 $*", args=true } # not sure if conflicting posix is an issue
```

Might be nice to also be able to have passthrough with subcommands so you can define a bit of a wrapper for extra arguments. E.g.,
```toml
[show]
command = "echo $@"
args = "*"
me = { command = "echo I am $(whoami)" }
```
